spring:
  application:
    name: ejemplo-redis
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
